// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0lScCOXfmbSObLvJv0lKX9C_njNsXY3g',
    appId: '1:730591130520:web:68d4cbdba2616d4d8a31ed',
    messagingSenderId: '730591130520',
    projectId: 'chatmessenger-7821d',
    authDomain: 'chatmessenger-7821d.firebaseapp.com',
    storageBucket: 'chatmessenger-7821d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT2b6kRtW6lNdubQ85EuGeBW9rHRNtOQY',
    appId: '1:730591130520:android:1c3efe61f5240d238a31ed',
    messagingSenderId: '730591130520',
    projectId: 'chatmessenger-7821d',
    storageBucket: 'chatmessenger-7821d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHC6lY-zLgQ5CAgNHJ831cO_PVPQZ11QA',
    appId: '1:730591130520:ios:ef4652e481be97eb8a31ed',
    messagingSenderId: '730591130520',
    projectId: 'chatmessenger-7821d',
    storageBucket: 'chatmessenger-7821d.appspot.com',
    iosBundleId: 'com.example.chatMenssager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHC6lY-zLgQ5CAgNHJ831cO_PVPQZ11QA',
    appId: '1:730591130520:ios:86ccb06ed3688fdc8a31ed',
    messagingSenderId: '730591130520',
    projectId: 'chatmessenger-7821d',
    storageBucket: 'chatmessenger-7821d.appspot.com',
    iosBundleId: 'com.example.chatMenssager.RunnerTests',
  );
}
